### ISSUE TITLE
IE / Edge issues

### ISSUE THREAD

**Issue by 1rosehip** [1rosehip/jplist-es6#3]

**Comment by 1rosehip** [comment]
Fixed using [babel-polyfill](https://babeljs.io/docs/en/babel-polyfill/) and CustomEvent [polyfill](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent)

**Comment by kimchristiansen** [comment]
I added the polyfill from this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
But fixing this issue will still not get it to work on ie11. ie11 throws the following error: _Symbol is undefined_

**Comment by akiessling** [comment]
I'm having the same issue as @kimchristiansen 
Were you able to solve this? Maybe through a customized jplist build?

**Comment by akiessling** [comment]
I updated babel and added some config for IE11 compatibility
https://github.com/extrameile/jplist-es6/commit/38c188611911c1ea3e3716144b381bc86cf8ef9d
Filtering and pagination now works, at the cost of additional 70kb JS code :/

**Comment by kimchristiansen** [comment]
I can't remember exactly what I did, but I think I added the following polyfill: https://cdnjs.com/libraries/babel-polyfill
